---
kind: Namespace
apiVersion: v1
metadata:
  name: aws-secretmapper
---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: secretmappings.aws-secretmapper.broadstripes.com
spec:
  group: aws-secretmapper.broadstripes.com
  version: v1
  names:
    kind: SecretMapping
    plural: secretmappings
    shortNames: ["sm"]
---
kind: CompositeController
apiVersion: metacontroller.k8s.io/v1alpha1
metadata:
  namespace: aws-secretmapper
  name: aws-secretmapper
spec:
  generateSelector: true
  parentResource:
    apiVersion: aws-secretmapper.broadstripes.com/v1
    resource: secretmappings
  childResources:
  - resource: secrets
    apiVersion: v1
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://webhook.aws-secretmapper/sync
