---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: secretmappings.aws-secretmapper.broadstripes.com
spec:
  group: aws-secretmapper.broadstripes.com
  version: v1
  names:
    kind: SecretMapping
    plural: secretmappings
    shortNames: ["sm"]
---
kind: CompositeController
apiVersion: metacontroller.k8s.io/v1alpha1
metadata:
  namespace: metacontroller
  name: aws-secretmapper
spec:
  generateSelector: true
  resyncPeriodSeconds: 300
  parentResource:
    apiVersion: aws-secretmapper.broadstripes.com/v1
    resource: secretmappings
  childResources:
  - resource: secrets
    apiVersion: v1
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://aws-secretmapper.metacontroller/sync
---
kind: Service
apiVersion: v1
metadata:
  namespace: metacontroller
  name: aws-secretmapper
spec:
  type: ClusterIP
  selector:
    app: aws-secretmapper
  ports:
    - port: 80
      targetPort: 4567
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: metacontroller
  name: aws-secretmapper
  labels:
    app: aws-secretmapper
spec:
  replicas: 1
  template:
    metadata:
      namespace: metacontroller
      labels:
        app: aws-secretmapper
    spec:
      containers:
        - name: webhook
          image: quay.io/broadstripes/aws-secretmapper
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: APP_ENV
              value: production
            - name: AWS_REGION
              value: us-east-1
